#pragma once
#include <iostream>
#include <stdint.h>
#include <allegro5/allegro.h>
#include <allegro5/allegro_primitives.h>
#include <math.h>
#include "imgui/imgui.h"
#include "imgui/imgui_impl_allegro5.h"
#include "colors.h"
#include "tinyexpr.h"